-- =========================================================
-- BusinessHub ERP - Seed Data
-- Engine: Microsoft SQL Server
--
-- Required reference data (default Roles, Permissions and their
-- mappings) is seeded by migration 0002_seed_auth_rbac.sql and is
-- applied automatically by `npm run db:migrate`.
--
-- This file is for optional DEVELOPMENT sample data only.
-- =========================================================

-- A sample admin user is intentionally NOT inserted here: PasswordHash
-- must be a real bcrypt hash. Once backend authentication lands
-- (Milestone 6), create the first admin via the registration flow or a
-- dedicated seed script that hashes the password, then assign the Admin
-- role, e.g.:
--
--   INSERT INTO dbo.UserRoles (UserId, RoleId)
--   SELECT u.Id, r.Id
--   FROM dbo.Users u CROSS JOIN dbo.Roles r
--   WHERE u.Email = 'admin@businesshub.local' AND r.Name = 'Admin';
